project:
  type: website
  execute-dir: project

  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Python Course"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme:
      light: flatly
      dark:  darkly
    css: styles.css
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

execute:
  freeze: auto
  cache:  false
  error:  true

editor: visual